name: Scrape comsumption info from electrical provider

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 9 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      env:
        ELECTRICAL_PROVIDER_USERNAME: ${{ secrets.ELECTRICAL_PROVIDER_USER }}
        ELECTRICAL_PROVIDER_PASSWORD: ${{ secrets.ELECTRICAL_PROVIDER_PWD }}
      run: mvn -B compile exec:java -Dexec.mainClass="scrape.App" -Dexec.args="$ELECTRICAL_PROVIDER_USERNAME $ELECTRICAL_PROVIDER_PWD naturgy.csv" --file pom.xml
