name: Scrape comsumption info from electrical provider

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Build
      env:
        ELECTRICAL_PROVIDER_USERNAME: ${{ secrets.ELECTRICAL_PROVIDER_USER }}
        ELECTRICAL_PROVIDER_PASSWORD: ${{ secrets.ELECTRICAL_PROVIDER_PWD }}
      run: mvn -B compile exec:java -Dexec.mainClass="scrape.App" -Dexec.args="$ELECTRICAL_PROVIDER_USERNAME $ELECTRICAL_PROVIDER_PASSWORD naturgy.csv" --file pom.xml
    - name: Commit and push 
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add naturgy.csv
        git commit -m "New data" || exit 0
        git push
    - name: Update temperatures        
      run: |-
        curl 'https://www.meteogalicia.gal/observacion/estacionshistorico/downloadcsv.action' --compressed -H 'Content-Type: application/x-www-form-urlencoded' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data "idIntervalo=3&idEstacion=19005&dataIni=16%2F12%2F19&dataFin=`date +%d%%2F%m%%2F%y`&idsMedida=30186&btn_exportar_csv=Res" -o temperatures.csv
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add temperatures.csv
        git commit -m "Latest temperatures" || exit 0
        git push
